import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import AuthProvider from '@/providers/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Next Crash',
    template: '%s | NextCrash',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Navbar />
          <div className="px-16 pt-8">{children}</div>
        </body>
      </AuthProvider>
    </html>
  );
}
